name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v2.6.1
      with:
        tags: filepattern:latest
        push: false
    
    - name: Download test data
      run: |
        wget https://github.com/USNISTGOV/MIST/wiki/testdata/Small_Fluorescent_Test_Dataset.zip
        unzip Small_Fluorescent_Test_Dataset.zip
    
    - uses: addnab/docker-run-action@v3
      with:
        image: filepattern:latest
        run: ./filepattern img_r0{yy}_c00{x+}.tif /data/Small_Fluorescent_Test_Dataset/image-tiles/
